name: Deploy To Foundry
on:
  workflow_dispatch:
    inputs:
      moduleId:
        description: 'Module Id'
        required: true
      moduleVersion:
        description: 'Module Version'
        required: true
      moduleManifest:
        description: 'Module Manifest Url'
        required: true
      moduleChangelog:
        description: 'Module Changelog Url'
        required: true
      moduleMinCore:
        description: 'Module Minimum Core Version'
        required: true
      moduleCompCore:
        description: 'Module Compatible Core Version'
        required: true

jobs:
  deploy:
    name: Push update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create node Environment
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Packages
        uses: bahmutov/npm-install@v1
      - name: Run Update Script
        run: node ./index.js
        env:
          FOUNDRY_USER: ${{ secrets.FOUNDRY_USER }}
          FOUNDRY_PWD: ${{ secrets.FOUNDRY_PWD }}
          MODULE_ID: ${{ github.event.inputs.moduleId }}
          MODULE_VERSION: ${{ github.event.inputs.moduleVersion }}
          MODULE_MANIFEST: ${{ github.event.inputs.moduleManifest }}
          MODULE_CHANGELOG: ${{ github.event.inputs.moduleChangelog }}
          MODULE_MIN_CORE: ${{ github.event.inputs.moduleMinCore }}
          MODULE_COMP_CORE: ${{ github.event.inputs.moduleCompCore }}
